// Copyright (C) 2015-2026 VMware, Inc. All Rights Reserved.
//
// Licensed under the GNU Lesser General Public License v2.1 (the "License");
// you may not use this file except in compliance with the License. The terms
// of the License are located in the COPYING file of this distribution.

const std = @import("std");

pub const C = @cImport({
    @cInclude("client_abi.h");
});

pub const CnfNode = extern struct {
    next: ?*CnfNode = null,
    name: ?[*:0]u8 = null,
    value: ?[*:0]u8 = null,
    first_child: ?*CnfNode = null,
    parent: ?*CnfNode = null,
};

pub const CmdArgs = extern struct {
    nAllDeps: c_int = 0,
    nAllowErasing: c_int = 0,
    nAssumeNo: c_int = 0,
    nAssumeYes: c_int = 0,
    nBest: c_int = 0,
    nCacheOnly: c_int = 0,
    nDebugSolver: c_int = 0,
    nShowHelp: c_int = 0,
    nRefresh: c_int = 0,
    nRpmVerbosity: c_int = 0,
    nShowDuplicates: c_int = 0,
    nShowVersion: c_int = 0,
    nNoDeps: c_int = 0,
    nNoGPGCheck: c_int = 0,
    nNoCmdLineGPGCheck: c_int = 0,
    nSkipSignature: c_int = 0,
    nSkipDigest: c_int = 0,
    nNoOutput: c_int = 0,
    nQuiet: c_int = 0,
    nVerbose: c_int = 0,
    nIPv4: c_int = 0,
    nIPv6: c_int = 0,
    nDisableExcludes: c_int = 0,
    nDownloadOnly: c_int = 0,
    nUrlsOnly: c_int = 0,
    nNoAutoRemove: c_int = 0,
    nJsonOutput: c_int = 0,
    nTestOnly: c_int = 0,
    nSkipBroken: c_int = 0,
    nSource: c_int = 0,
    nBuildDeps: c_int = 0,
    pszArch: ?[*:0]u8 = null,
    pszDownloadDir: ?[*:0]u8 = null,
    pszInstallRoot: ?[*:0]u8 = null,
    pszConfFile: ?[*:0]u8 = null,
    pszReleaseVer: ?[*:0]u8 = null,
    ppszCmds: ?[*]?[*:0]u8 = null,
    nCmdCount: c_int = 0,
    cn_setopts: ?*CnfNode = null,
    cn_repoopts: ?*CnfNode = null,
    nArgc: c_int = 0,
    ppszArgv: ?[*]?[*:0]u8 = null,
};

pub const Conf = extern struct {
    nGPGCheck: c_int = 0,
    nCliGPGCheck: c_int = 0,
    nSSLVerify: c_int = 0,
    nInstallOnlyLimit: c_int = 0,
    nCleanRequirementsOnRemove: c_int = 0,
    nKeepCache: c_int = 0,
    nOpenMax: c_int = 0,
    nCheckUpdateCompat: c_int = 0,
    nDistroSyncReinstallChanged: c_int = 0,
    nConnectTimeout: c_int = 0,
    rpmTransFlags: u32 = 0,
    nPluginsEnabled: c_int = 0,
    nSkipDigest: c_int = 0,
    nSkipSignature: c_int = 0,
    pszRepoDir: ?[*:0]u8 = null,
    pszCacheDir: ?[*:0]u8 = null,
    pszPersistDir: ?[*:0]u8 = null,
    pszProxy: ?[*:0]u8 = null,
    pszProxyUserPass: ?[*:0]u8 = null,
    ppszDistroVerPkgs: ?[*]?[*:0]u8 = null,
    pszBaseArch: ?[*:0]u8 = null,
    pszVarReleaseVer: ?[*:0]u8 = null,
    pszVarBaseArch: ?[*:0]u8 = null,
    pszUserAgentHeader: ?[*:0]u8 = null,
    pszOSName: ?[*:0]u8 = null,
    pszOSVersion: ?[*:0]u8 = null,
    ppszExcludes: ?[*]?[*:0]u8 = null,
    ppszMinVersions: ?[*]?[*:0]u8 = null,
    ppszPkgLocks: ?[*]?[*:0]u8 = null,
    ppszProtectedPkgs: ?[*]?[*:0]u8 = null,
    ppszInstallOnlyPkgs: ?[*]?[*:0]u8 = null,
    ppszVarsDirs: ?[*]?[*:0]u8 = null,
    pszPluginPath: ?[*:0]u8 = null,
    pszPluginConfPath: ?[*:0]u8 = null,
};

pub const RepoData = extern struct {
    nEnabled: c_int = 0,
    nSkipIfUnavailable: c_int = 0,
    nGPGCheck: c_int = 0,
    nHasMetaData: c_int = 0,
    lMetadataExpire: c_long = 0,
    pszId: ?[*:0]u8 = null,
    pszName: ?[*:0]u8 = null,
    ppszBaseUrls: ?[*]?[*:0]u8 = null,
    pszMetaLink: ?[*:0]u8 = null,
    pszMirrorList: ?[*:0]u8 = null,
    pszSnapshotUrl: ?[*:0]u8 = null,
    pszSnapshotFile: ?[*:0]u8 = null,
    ppszUrlGPGKeys: ?[*]?[*:0]u8 = null,
    nSSLVerify: c_int = 0,
    pszSSLCaCert: ?[*:0]u8 = null,
    pszSSLClientCert: ?[*:0]u8 = null,
    pszSSLClientKey: ?[*:0]u8 = null,
    pszUser: ?[*:0]u8 = null,
    pszPass: ?[*:0]u8 = null,
    nPriority: c_int = 0,
    nTimeout: c_long = 0,
    nMinrate: c_long = 0,
    nThrottle: c_long = 0,
    nRetries: c_int = 0,
    nSkipMDFileLists: c_int = 0,
    nSkipMDUpdateInfo: c_int = 0,
    nSkipMDOther: c_int = 0,
    pszCacheName: ?[*:0]u8 = null,
    pRepo: ?*anyopaque = null,
    pNext: ?*RepoData = null,
};

pub const Tdnf = extern struct {
    pSack: ?*anyopaque = null,
    pArgs: ?*CmdArgs = null,
    pConf: ?*Conf = null,
    pRpmConfig: ?*anyopaque = null,
    pRepos: ?*RepoData = null,
    pCmdLineRepo: ?*anyopaque = null,
    pPlugins: ?*anyopaque = null,
    ppszRepoFromDirIds: ?[*]?[*:0]u8 = null,
    pRequestTrace: ?*anyopaque = null,
    pTransactionPlanState: ?*anyopaque = null,
    ppszHiddenRefs: ?[*]?[*:0]u8 = null,
    dwHiddenRefCount: u32 = 0,
    pdwCmdLinePkgIds: ?[*]u32 = null,
    ppszCmdLinePkgPaths: ?[*]?[*:0]u8 = null,
    dwCmdLinePkgCount: u32 = 0,
    nTestReloadFailureStage: u32 = 0,
};

pub const DownloadProgressFn = *const fn (
    userdata: ?*anyopaque,
    dltotal: i64,
    dlnow: i64,
    ultotal: i64,
    ulnow: i64,
) callconv(.c) c_int;

pub const DownloadRequest = extern struct {
    pszUrl: ?[*:0]const u8,
    pszDestination: ?[*:0]const u8,
    pfnProgress: ?DownloadProgressFn,
    pProgressData: ?*anyopaque,
    pszUserAgent: ?[*:0]const u8,
    pszProxy: ?[*:0]const u8,
    pszProxyUserPwd: ?[*:0]const u8,
    pszUserName: ?[*:0]const u8,
    pszPassword: ?[*:0]const u8,
    pszSSLCaCert: ?[*:0]const u8,
    pszSSLClientCert: ?[*:0]const u8,
    pszSSLClientKey: ?[*:0]const u8,
    nSSLVerify: c_int,
    nConnectTimeout: c_long,
    nTimeout: c_long,
    nLowSpeedLimit: c_long,
    nLowSpeedTime: c_long,
    nMaxRecvSpeed: c_long,
};

fn assertLayout(comptime Zig: type, comptime Header: type, comptime fields: anytype) void {
    std.debug.assert(@sizeOf(Zig) == @sizeOf(Header));
    std.debug.assert(@alignOf(Zig) == @alignOf(Header));
    inline for (fields) |field| {
        std.debug.assert(@offsetOf(Zig, field) == @offsetOf(Header, field));
    }
}

comptime {
    assertLayout(CnfNode, C.struct_cnfnode, .{
        "next",
        "name",
        "value",
        "first_child",
        "parent",
    });
    assertLayout(CmdArgs, C.TDNF_CMD_ARGS, .{
        "nAllDeps",
        "nAllowErasing",
        "nAssumeNo",
        "nAssumeYes",
        "nBest",
        "nCacheOnly",
        "nDebugSolver",
        "nShowHelp",
        "nRefresh",
        "nRpmVerbosity",
        "nShowDuplicates",
        "nShowVersion",
        "nNoDeps",
        "nNoGPGCheck",
        "nNoCmdLineGPGCheck",
        "nSkipSignature",
        "nSkipDigest",
        "nNoOutput",
        "nQuiet",
        "nVerbose",
        "nIPv4",
        "nIPv6",
        "nDisableExcludes",
        "nDownloadOnly",
        "nUrlsOnly",
        "nNoAutoRemove",
        "nJsonOutput",
        "nTestOnly",
        "nSkipBroken",
        "nSource",
        "nBuildDeps",
        "pszArch",
        "pszDownloadDir",
        "pszInstallRoot",
        "pszConfFile",
        "pszReleaseVer",
        "ppszCmds",
        "nCmdCount",
        "cn_setopts",
        "cn_repoopts",
        "nArgc",
        "ppszArgv",
    });
    assertLayout(Conf, C.TDNF_CONF, .{
        "nGPGCheck",
        "nCliGPGCheck",
        "nSSLVerify",
        "nInstallOnlyLimit",
        "nCleanRequirementsOnRemove",
        "nKeepCache",
        "nOpenMax",
        "nCheckUpdateCompat",
        "nDistroSyncReinstallChanged",
        "nConnectTimeout",
        "rpmTransFlags",
        "nPluginsEnabled",
        "nSkipDigest",
        "nSkipSignature",
        "pszRepoDir",
        "pszCacheDir",
        "pszPersistDir",
        "pszProxy",
        "pszProxyUserPass",
        "ppszDistroVerPkgs",
        "pszBaseArch",
        "pszVarReleaseVer",
        "pszVarBaseArch",
        "pszUserAgentHeader",
        "pszOSName",
        "pszOSVersion",
        "ppszExcludes",
        "ppszMinVersions",
        "ppszPkgLocks",
        "ppszProtectedPkgs",
        "ppszInstallOnlyPkgs",
        "ppszVarsDirs",
        "pszPluginPath",
        "pszPluginConfPath",
    });
    assertLayout(RepoData, C.TDNF_REPO_DATA, .{
        "nEnabled",
        "nSkipIfUnavailable",
        "nGPGCheck",
        "nHasMetaData",
        "lMetadataExpire",
        "pszId",
        "pszName",
        "ppszBaseUrls",
        "pszMetaLink",
        "pszMirrorList",
        "pszSnapshotUrl",
        "pszSnapshotFile",
        "ppszUrlGPGKeys",
        "nSSLVerify",
        "pszSSLCaCert",
        "pszSSLClientCert",
        "pszSSLClientKey",
        "pszUser",
        "pszPass",
        "nPriority",
        "nTimeout",
        "nMinrate",
        "nThrottle",
        "nRetries",
        "nSkipMDFileLists",
        "nSkipMDUpdateInfo",
        "nSkipMDOther",
        "pszCacheName",
        "pRepo",
        "pNext",
    });
    assertLayout(Tdnf, C.TDNF, .{
        "pSack",
        "pArgs",
        "pConf",
        "pRpmConfig",
        "pRepos",
        "pCmdLineRepo",
        "pPlugins",
        "ppszRepoFromDirIds",
        "pRequestTrace",
        "pTransactionPlanState",
        "ppszHiddenRefs",
        "dwHiddenRefCount",
        "pdwCmdLinePkgIds",
        "ppszCmdLinePkgPaths",
        "dwCmdLinePkgCount",
        "nTestReloadFailureStage",
    });
    assertLayout(DownloadRequest, C.TDNF_ZIG_DOWNLOAD_REQUEST, .{
        "pszUrl",
        "pszDestination",
        "pfnProgress",
        "pProgressData",
        "pszUserAgent",
        "pszProxy",
        "pszProxyUserPwd",
        "pszUserName",
        "pszPassword",
        "pszSSLCaCert",
        "pszSSLClientCert",
        "pszSSLClientKey",
        "nSSLVerify",
        "nConnectTimeout",
        "nTimeout",
        "nLowSpeedLimit",
        "nLowSpeedTime",
        "nMaxRecvSpeed",
    });
}
