pub const LegacyPackage = extern struct {
    dwEpoch: u32,
    dwInstallSizeBytes: u32,
    dwDownloadSizeBytes: u32,
    nChecksumType: c_int,
    pszName: ?[*:0]const u8,
    pszRepoName: ?[*:0]const u8,
    pszVersion: ?[*:0]const u8,
    pszArch: ?[*:0]const u8,
    pszEVR: ?[*:0]const u8,
    pszSummary: ?[*:0]const u8,
    pszURL: ?[*:0]const u8,
    pszLicense: ?[*:0]const u8,
    pszDescription: ?[*:0]const u8,
    pszFormattedSize: ?[*:0]const u8,
    pszFormattedDownloadSize: ?[*:0]const u8,
    pszRelease: ?[*:0]const u8,
    pszLocation: ?[*:0]const u8,
    pppszDependencies: ?*anyopaque,
    ppszFileList: ?*anyopaque,
    pszSourcePkg: ?[*:0]const u8,
    pbChecksum: ?*anyopaque,
    pChangeLogEntries: ?*anyopaque,
    pNext: [*c]LegacyPackage,
};

pub const LegacyResult = extern struct {
    nNeedAction: c_int,
    nNeedDownload: c_int,
    nAlterType: c_int,
    pPkgsNotAvailable: [*c]LegacyPackage,
    pPkgsExisting: [*c]LegacyPackage,
    pPkgsToInstall: [*c]LegacyPackage,
    pPkgsToDowngrade: [*c]LegacyPackage,
    pPkgsToUpgrade: [*c]LegacyPackage,
    pPkgsToRemove: [*c]LegacyPackage,
    pPkgsUnNeeded: [*c]LegacyPackage,
    pPkgsToReinstall: [*c]LegacyPackage,
    pPkgsObsoleted: [*c]LegacyPackage,
    pPkgsRemovedByDowngrade: [*c]LegacyPackage,
    ppszPkgsNotResolved: ?*anyopaque,
    ppszPkgsUserInstall: ?*anyopaque,
};

pub const Comparison = extern struct {
    dwStatus: u32,
    dwReason: u32,
    dwActionKind: u32,
    dwDifferenceIndex: u32,
    dwNativeCount: u32,
    dwLegacyCount: u32,
};
